### ISSUE TITLE
missing castling requirements

### ISSUE THREAD

**Issue by PatheticMustan** [KryptoCrash/chessgame#1]
https://github.com/KryptoCrash/chessgame/blob/95f5c7cb0a0ab2a1d4d13ea6ca0933313d55d4cd/src/Board.h#L25-L34

https://en.wikipedia.org/wiki/Castling

> Neither the king nor the chosen rook has previously moved.

**Comment by KryptoCrash** [comment]
Uh this works though lol

**Comment by PatheticMustan** [comment]
OH castlePos stays the whole game
:P uhhhhhhhhhhhhhh sorry sorry
